package api

import (
	"net/http"

	"github.com/HengXin666/HX-ProxyGroup/internal/listener"
)

// capabilityEndpoints returns the endpoints section of the catalog. It is data only: see capabilities.go for the types and the live enum wiring.
func capabilityEndpoints() []CapabilityEndpoint {
	return []CapabilityEndpoint{
		{
			ID:          "capabilities.read",
			Method:      http.MethodGet,
			Path:        CapabilityCatalogPath,
			Summary:     "This document. Read it first: it lists every management endpoint with its fields, closed enums and an accepted example, so no Go source needs to be read to drive this API.",
			Auth:        "api-key",
			ResponseRef: "The capability catalog: namespaces, enums, endpoints, workflows and the product boundary.",
		},
		{
			ID:      "quickstart.create",
			Method:  http.MethodPost,
			Path:    QuickstartPath,
			Summary: "Reach a published proxy in one call: register and refresh the source, then create the proxy group and its listener. Prefer this over the four-call flow when the caller has no existing nodes.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true, Description: "Name for the resulting group and listener.", Example: "hk-pool"},
				{Name: "subscription_url", Type: "string", Description: "Remote subscription to register and refresh inline. Mutually exclusive with subscription_ids.", Example: "https://example.com/sub?token=x", SeeAlso: []string{"subscription.create", "subscription.refresh"}},
				{Name: "subscription_name", Type: "string", Description: "Name for the subscription created from subscription_url. Defaults to name."},
				{Name: "subscription_ids", Type: "array<string>", Description: "Reuse already-refreshed subscriptions. The caller is responsible for refreshing them first.", SeeAlso: []string{"subscription.refresh"}},
				{Name: "node_ids", Type: "array<string>", Description: "Select explicit nodes instead of a subscription."},
				{Name: "strategy", Type: "string", Enum: "proxy_group_strategy", Description: "Selection strategy. Omitted uses the service default."},
				{Name: "limit", Type: "integer", Description: "Cap how many members the group keeps. 0 keeps every match."},
				{Name: "kind", Type: "string", Enum: "listener_kind", Default: "mixed", Description: "Protocol to publish."},
				{Name: "bind_address", Type: "string", Default: "127.0.0.1", Description: "Bind address. Loopback by default so exposure is deliberate."},
				{Name: "port", Type: "integer", Default: 7890, Description: "Listen port. In shared-inbound mode the aggregate entry point owns the port and this value is ignored."},
				{Name: "auth", Type: "object", Description: "Username/password for the published service. Required for a non-loopback bind and for advanced kinds."},
				{Name: "public_endpoint", Type: "object", Description: "Externally reachable endpoint for a loopback bind. Non-advanced kinds only."},
				{Name: "transport", Type: "object", Description: "Transport override; required for advanced kinds."},
			},
			Example: map[string]any{
				"name":             "hk-pool",
				"subscription_url": "https://example.com/sub?token=x",
				"strategy":         "url-test",
				"kind":             "mixed",
				"port":             7890,
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_quickstart", Meaning: "The request is missing a source or mixes mutually exclusive fields.", Remediation: "Provide exactly one of subscription_url, subscription_ids, or node_ids."},
				{Status: 422, Code: "quickstart_failed", Meaning: "A step failed after the request was accepted. Everything this call created is removed first, so an error never leaves a half-built service.", Remediation: "Read the message: it names the failing step."},
			},
			ResponseRef: "The created group and listener, plus share_path and consumer_nodes_path.",
			SeeAlso:     []string{"capabilities.read", "listener.share.read"},
		},
		{
			ID:      "proxy_service.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/proxy-services",
			Summary: "Create a proxy group and its listener in one call. This is the fast path to a working proxy: the group selects nodes and the listener publishes them.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true, Description: "Display name. Also used to name the generated listener.", Example: "hk-pool"},
				{Name: "strategy", Type: "string", Required: true, Enum: "proxy_group_strategy", Description: "Selection strategy.", Example: "url-test"},
				{Name: "empty_behavior", Type: "string", Enum: "empty_behavior", Default: "fail-closed", Description: "Behaviour when the source selects no node.", Example: "fail-closed"},
				{Name: "enabled", Type: "boolean", Default: true, Description: "Whether the group starts enabled."},
				{Name: "source_spec", Type: "object", Required: true, Description: "Which nodes become members. See source_spec.* fields.", Example: map[string]any{"subscription_ids": []string{"<subscription-id>"}, "sort_by": "latency", "limit": 20}},
				{Name: "listener", Type: "object", Required: true, Description: "How the service is published. See listener.* fields.", Example: map[string]any{"name": "hk-pool", "kind": "mixed", "bind_address": "127.0.0.1", "port": 7890}},
				{Name: "source_spec.allow_empty", Type: "boolean", Description: "Permit a deliberately dormant fail-closed group.", Default: false},
				{Name: "source_spec.node_ids", Type: "array<string>", Description: "Explicit node ids."},
				{Name: "source_spec.group_ids", Type: "array<string>", Description: "Other groups used as members, enabling serial fallback and parallel composition. References must stay acyclic.", SeeAlso: []string{"proxy_group.create"}},
				{Name: "source_spec.subscription_ids", Type: "array<string>", Description: "Subscriptions whose current nodes become members.", SeeAlso: []string{"subscription.create", "subscription.refresh"}},
				{Name: "source_spec.name_keywords", Type: "array<string>", Description: "Substring filters on node name."},
				{Name: "source_spec.regions", Type: "array<string>", Description: "Region filters, upper-cased before matching."},
				{Name: "source_spec.protocols", Type: "array<string>", Description: "Protocol filters.", Enum: "node_protocol"},
				{Name: "source_spec.states", Type: "array<string>", Description: "Probe state filters.", Enum: "node_state"},
				{Name: "source_spec.max_latency_ms", Type: "integer", Description: "Drop members slower than this. 0..60000; 0 disables the filter."},
				{Name: "source_spec.sort_by", Type: "string", Enum: "sort_by", Default: "latency", Description: "Member ordering. Defaults to latency when a subscription is used."},
				{Name: "source_spec.limit", Type: "integer", Description: "Keep at most this many members. 0..500."},
				{Name: "source_spec.include_direct", Type: "boolean", Description: "Append a DIRECT member."},
				{Name: "source_spec.test_url", Type: "string", Description: "Health-check URL for non-manual strategies. Defaults to the built-in generate_204 URL; must be http or https."},
				{Name: "source_spec.interval_seconds", Type: "integer", Description: "Health-check interval for non-manual strategies. 30..86400; defaults to 300."},
				{Name: "listener.name", Type: "string", Description: "Listener name. Falls back to the service name."},
				{Name: "listener.kind", Type: "string", Required: true, Enum: "listener_kind", Description: "Protocol to publish.", Example: "mixed"},
				{Name: "listener.bind_address", Type: "string", Required: true, Description: "Bind address. Advanced kinds must bind loopback because the edge relay reaches them locally. A non-loopback bind requires credentials.", Example: "127.0.0.1"},
				{Name: "listener.port", Type: "integer", Required: true, Description: "Listen port. Ignored when the protocol family is served by the shared inbound; the aggregate row owns the port and members are selected by username.", Example: 7890},
				{Name: "listener.auth", Type: "object", Description: "Username/password for the published service. Required for a non-loopback bind and for every advanced kind.", Example: map[string]any{"username": "hx", "password": "<generated>"}},
				{Name: "listener.transport", Type: "object", Description: "Transport override. Required for advanced kinds.", Example: map[string]any{"type": "ws", "ws_path": "/__hx-proxy__/<random>"}},
				{Name: "listener.transport.type", Type: "string", Enum: "listener_transport", Description: "Transport type."},
				{Name: "listener.transport.ws_path", Type: "string", Description: "WebSocket path. Must start with the reserved prefix " + listener.WebSocketPathPrefix + ". Required for " + "\"ws\"."},
				{Name: "listener.public_endpoint", Type: "object", Description: "Externally reachable endpoint for a loopback-bound listener. Non-advanced kinds only.", Example: map[string]any{"host": "proxy.example.com", "port": 443, "tls": true}},
				{Name: "listener.public_endpoint.host", Type: "string", Description: "Public IP or domain. Loopback and unspecified addresses are rejected."},
				{Name: "listener.public_endpoint.port", Type: "integer", Description: "Public port. Defaults to the listen port."},
				{Name: "listener.public_endpoint.tls", Type: "boolean", Description: "Whether the public endpoint terminates TLS."},
				{Name: "listener.enabled", Type: "boolean", Default: true, Description: "Whether the listener starts enabled."},
			},
			Example: map[string]any{
				"name":           "hk-pool",
				"strategy":       "url-test",
				"empty_behavior": "fail-closed",
				"source_spec":    map[string]any{"subscription_ids": []string{"<subscription-id>"}, "sort_by": "latency", "limit": 20},
				"listener": map[string]any{
					"name": "hk-pool", "kind": "mixed",
					"bind_address": "127.0.0.1", "port": 7890,
					"auth": map[string]any{"username": "hx", "password": "<generated>"},
				},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "proxy_service_create_failed", Meaning: "The group or its listener was rejected. The proxy group is rolled back, so nothing half-created remains.", Remediation: "Read the message: it names the offending field."},
				{Status: 400, Code: "invalid_request", Meaning: "The body did not decode, or contained an unknown field.", Remediation: "Send only the documented fields; unknown fields are rejected, not ignored."},
			},
			ResponseRef: "Returns the created group and listener, including the listener's share_path.",
			SeeAlso:     []string{"listener.share.read", "consumer_nodes.read"},
		},
		{
			ID:      "backup.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/backups",
			Summary: "Write a consistent snapshot of the control-plane database. Take one before a bulk change so the previous state is restorable.",
			Auth:    "api-key",
			Errors: []CapabilityError{
				{Status: 503, Code: "busy", Meaning: "Another backup or restore is in progress."},
			},
			ResponseRef: "Returns the artifact record with its id and size.",
		},
		{
			ID:          "export.create",
			Method:      http.MethodPost,
			Path:        "/api/v1/exports",
			Summary:     "Export the portable configuration (groups, listeners and their desired state) as an artifact. Unlike a backup, an export is meant to be moved to another installation.",
			Auth:        "api-key",
			ResponseRef: "Returns the artifact record with its id and size.",
		},
		{
			ID:      "subscription.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/subscriptions",
			Summary: "Register a node source. Creating it does not fetch it: call the refresh endpoint before a group can select its nodes.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true, Description: "Display name.", Example: "vendor-hk"},
				{Name: "source_type", Type: "string", Required: true, Enum: "subscription_source_type", Description: "Where the node list comes from.", Example: "remote"},
				{Name: "source_config", Type: "object", Required: true, Description: "Source-specific settings."},
				{Name: "source_config.url", Type: "string", Description: "Required when source_type is remote. Must be http or https.", Example: "https://example.com/sub?token=x"},
				{Name: "source_config.headers", Type: "object", Description: "Extra request headers for a remote fetch."},
				{Name: "source_config.user_agent", Type: "string", Description: "User-Agent for a remote fetch."},
				{Name: "source_config.inline", Type: "string", Description: "Required when source_type is inline: the subscription document itself."},
				{Name: "source_config.file_path", Type: "string", Description: "Required when source_type is file."},
				{Name: "source_config.timeout_seconds", Type: "integer", Description: "Fetch timeout."},
				{Name: "source_config.allow_private", Type: "boolean", Description: "Permit fetching a private address. Off by default because the fetch is SSRF-sensitive."},
				{Name: "enabled", Type: "boolean", Default: true, Description: "Whether the subscription starts enabled."},
				{Name: "refresh_interval_seconds", Type: "integer", Description: "Automatic refresh interval. Omit for manual refresh only."},
				{Name: "refresh_cron", Type: "string", Description: "Cron expression for refresh, as an alternative to an interval."},
			},
			Example: map[string]any{
				"name": "vendor-hk", "source_type": "remote",
				"source_config": map[string]any{"url": "https://example.com/sub?token=x"},
			},
			Errors: []CapabilityError{
				{Status: 400, Code: "invalid_request", Meaning: "The body did not decode or carried an unknown field."},
				{Status: 422, Code: "invalid_subscription", Meaning: "The source configuration failed validation.", Remediation: "Check that source_config matches source_type."},
			},
			SeeAlso: []string{"subscription.refresh"},
		},
		{
			ID:      "subscription.refresh",
			Method:  http.MethodPost,
			Path:    "/api/v1/subscriptions/<subscription-id>/refresh",
			Summary: "Fetch the source now and store a snapshot. This is the step that makes the nodes exist; until it succeeds, a group that references the subscription selects nothing.",
			Auth:    "api-key",
			PathParams: []string{
				"subscription-id: id returned by subscription.create",
			},
			Errors: []CapabilityError{
				{Status: 404, Code: "not_found", Meaning: "No such subscription."},
				{Status: 502, Code: "refresh_failed", Meaning: "The fetch or parse failed. The previous snapshot is kept, so a failed refresh never empties a working group.", Remediation: "Retry, or check the source URL and reachability."},
			},
			ResponseRef: "Returns the snapshot id, detected format, and estimated node count.",
		},
		{
			ID:          "node.list",
			Method:      http.MethodGet,
			Path:        "/api/v1/nodes",
			Summary:     "List known nodes and their probe state. Use it to confirm a refresh produced members before creating a group.",
			Auth:        "api-key",
			ResponseRef: "Array of nodes with protocol, region, state, and last measured latency.",
		},
		{
			ID:          "node_settings.read",
			Method:      http.MethodGet,
			Path:        "/api/v1/node-settings",
			Summary:     "Read the global probe thresholds: how many consecutive failures quarantine a node, and the latency bounds that separate healthy from degraded.",
			Auth:        "api-key",
			ResponseRef: "The probe quality settings.",
			SeeAlso:     []string{"node.list"},
		},
		{
			ID:      "proxy_group.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/proxy-groups",
			Summary: "Create a group without a listener. Use it to compose groups (for example a fallback chain) before publishing them.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true, Description: "Display name."},
				{Name: "strategy", Type: "string", Required: true, Enum: "proxy_group_strategy", Description: "Selection strategy."},
				{Name: "source_spec", Type: "object", Required: true, Description: "Member selection. Same fields as the proxy service source_spec."},
				{Name: "enabled", Type: "boolean", Default: true},
				{Name: "empty_behavior", Type: "string", Enum: "empty_behavior", Default: "fail-closed"},
				{Name: "fallback_target_id", Type: "string", Description: "Group to fall back to when empty_behavior is not enough."},
				{Name: "dialer_proxy_group_id", Type: "string", Description: "Group this group's egress is tunnelled through, at any depth. Every member this group selects is dialled through that group. The target must exist, be enabled, and must not close a cycle; a group that also sets source_spec.include_direct is rejected because DIRECT would bypass the chain. This is the group-level chain; upstream_proxy_group_id on a provider is the node-level equivalent."},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_proxy_group", Meaning: "Validation failed, for example a disabled or missing referenced group, or a reference cycle.", Remediation: "Read the message; it names the group that broke the reference."},
			},
		},
		{
			ID:      "listener.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/listeners",
			Summary: "Publish an existing group on a port. Prefer proxy_service.create unless the group already exists.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true},
				{Name: "kind", Type: "string", Required: true, Enum: "listener_kind"},
				{Name: "bind_address", Type: "string", Required: true, Description: "Advanced kinds must bind loopback; a non-loopback bind requires auth."},
				{Name: "port", Type: "integer", Required: true},
				{Name: "proxy_group_id", Type: "string", Required: true, Description: "Group whose members this listener serves."},
				{Name: "auth", Type: "object", Description: "Required for a non-loopback bind and for advanced kinds."},
				{Name: "transport", Type: "object", Description: "Required for advanced kinds; type must be ws."},
				{Name: "public_endpoint", Type: "object", Description: "Externally reachable endpoint for a loopback bind. Non-advanced kinds only."},
				{Name: "enabled", Type: "boolean", Default: true},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_listener", Meaning: "Validation failed: unknown kind, missing credential on a public bind, advanced kind without ws transport, or a loopback public_endpoint host.", Remediation: "For a loopback listener reached through a reverse proxy, set public_endpoint to the name clients use."},
			},
		},
		{
			ID:          "listener.share.read",
			Method:      http.MethodGet,
			Path:        "/api/v1/listeners",
			Summary:     "Read listeners to obtain the share_path of the one just published. The share token in that path is the consumer credential.",
			Auth:        "api-key",
			ResponseRef: "Each listener exposes share_path, plus shared_inbound when it is served by an aggregate entry point.",
		},
		{
			ID:      "consumer_nodes.read",
			Method:  http.MethodGet,
			Path:    listener.ConsumerNodesPath + "<share-token>",
			Summary: "Read the frozen node listing a consumer program uses to dial nodes itself. Token-addressed, so it needs no API key.",
			Auth:    "token in path",
			Fields: []CapabilityField{
				{Name: "share-token", Type: "string", Required: true, Description: "The final segment of the listener share_path. 16..64 characters."},
			},
			Errors: []CapabilityError{
				{Status: 404, Code: "not_found", Meaning: "The token is unknown, the listener is disabled, or the listener has no externally reachable endpoint. All three collapse into one reply so listener existence cannot be probed."},
				{Status: 405, Code: "method_not_allowed", Meaning: "Only GET is served; the listing is a pure read."},
			},
			SeeAlso: []string{"docs/CONSUMER_INTEGRATION_CONTRACT.md"},
		},
		{
			ID:      "residential.provider.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/residential/providers",
			Summary: "Register a residential vendor gateway. Chaining is configured here: upstream_proxy_group_id makes every node of this provider reach the vendor through that group.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true},
				{Name: "vendor", Type: "string", Required: true, Description: "Vendor key. Known presets: bestproxy, rapidproxy. Other keys are accepted but the username template must be supplied explicitly.", Example: "bestproxy"},
				{Name: "protocol", Type: "string", Required: true, Enum: "residential_provider_protocol", Description: "Gateway protocol the data plane dials."},
				{Name: "gateway_host", Type: "string", Required: true, Description: "Vendor gateway host."},
				{Name: "gateway_port", Type: "integer", Required: true, Description: "Vendor gateway port."},
				{Name: "upstream_proxy_group_id", Type: "string", Description: "Group this provider dials through, so the vendor gateway is reachable only via that group. This is the node-level chain, baked into every auto-minted node of the provider; proxy_group.create's dialer_proxy_group_id is the group-level equivalent, set per curated group. Both must name an existing, enabled group. The id is resolved to a display name only while compiling the data-plane config, so it never reaches a consumer.", SeeAlso: []string{"proxy_group.create", "proxy_service.create"}},
				{Name: "api_url", Type: "string", Description: "Vendor API base URL, for api-list and cf-worker rotation."},
				{Name: "worker_url", Type: "string", Description: "Cloudflare Worker panel URL, for cf-worker rotation."},
				{Name: "api_proxy_url", Type: "string", Description: "Proxy used to reach the vendor API."},
				{Name: "credentials", Type: "object", Description: "Vendor credentials. Stored encrypted and never returned."},
				{Name: "username_template", Type: "string", Description: "Vendor username pattern. Placeholders are documented by the presets endpoint.", SeeAlso: []string{"residential.presets.read"}},
				{Name: "rotation_mode", Type: "string", Enum: "residential_rotation_mode", Description: "How the vendor hands out a new exit."},
				{Name: "session_ttl_seconds", Type: "integer", Description: "Sticky session lifetime. Validated per vendor and rotation mode."},
				{Name: "max_concurrent_sessions", Type: "integer", Description: "Cap on concurrently allocated sessions."},
				{Name: "pool_size", Type: "integer", Description: "How many exit endpoints to preallocate."},
				{Name: "session_expiry_policy", Type: "string", Description: "What happens when a session expires."},
				{Name: "default_region", Type: "string", Description: "Default region."},
				{Name: "default_region_mode", Type: "string", Enum: "residential_region_mode", Default: "fixed"},
				{Name: "default_random_regions", Type: "array<string>", Description: "Candidate regions when the region mode is application-random. At most 64."},
				{Name: "enabled", Type: "boolean", Default: true},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_residential_provider", Meaning: "Validation failed, including an unknown or disabled upstream_proxy_group_id.", Remediation: "Create and enable the group before referencing it."},
			},
			SeeAlso: []string{"residential.channel.create", "residential.presets.read"},
		},
		{
			ID:      "residential.channel.create",
			Method:  http.MethodPost,
			Path:    "/api/v1/residential/channels",
			Summary: "Publish residential exits as a consumer-facing channel with a control token. The consumer mints sessions against /ctl/ and the control plane allocates whichever exit is currently live.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "name", Type: "string", Required: true},
				{Name: "provider_id", Type: "string", Required: true},
				{Name: "provider_ids", Type: "array<string>", Description: "Additional providers aggregated into the same channel. provider_id is included automatically."},
				{Name: "mode", Type: "string", Description: "How exits are handed out. The supported modes are passthrough and sticky; sticky pins one exit per session.", Example: "sticky"},
				{Name: "proxy_group_id", Type: "string", Description: "Group the channel's nodes belong to."},
				{Name: "region", Type: "string"},
				{Name: "region_mode", Type: "string", Enum: "residential_region_mode"},
				{Name: "random_regions", Type: "array<string>"},
				{Name: "session_count", Type: "integer", Description: "How many sessions to keep ready."},
				{Name: "idle_release_seconds", Type: "integer", Description: "Release a session after this much inactivity."},
				{Name: "preallocate", Type: "boolean", Description: "Allocate exits ahead of the first request."},
				{Name: "listener", Type: "object", Description: "Listener to publish the channel on, with kind, bind_address, port, auth, and transport."},
				{Name: "enabled", Type: "boolean", Default: true},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_residential_channel", Meaning: "Validation failed, often an unknown provider or an unsupported region mode combination."},
			},
			SeeAlso: []string{"residential.provider.create", "residential.ctl"},
		},
		{
			ID:          "settings.read",
			Method:      http.MethodGet,
			Path:        "/api/v1/settings",
			Summary:     "Read the global settings, including whether services are published on their own ports or through the shared inbound entry points. Read this before creating a listener: in shared mode the port you pass is ignored and the aggregate row owns it.",
			Auth:        "api-key",
			ResponseRef: "The settings document, including shared_inbound.",
			SeeAlso:     []string{"settings.update", "listener.create"},
		},
		{
			ID:      "settings.update",
			Method:  http.MethodPut,
			Path:    "/api/v1/settings",
			Summary: "Replace the global settings. A change here converges the shared inbound rows on the next apply.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "shared_inbound.mode", Type: "string", Description: "per_service gives every service its own port; shared collapses the standard family onto one Mixed port and the websocket family onto one WS port.", Example: "shared"},
				{Name: "shared_inbound.mixed_bind_address", Type: "string", Description: "Bind address for the shared Mixed listener."},
				{Name: "shared_inbound.mixed_port", Type: "integer", Description: "Port for the shared Mixed listener.", Example: 7890},
				{Name: "shared_inbound.ws_port", Type: "integer", Description: "Port for the shared websocket listener.", Example: 7891},
				{Name: "shared_inbound.mixed_public_host", Type: "string", Description: "Externally advertised host for the shared Mixed listener."},
				{Name: "shared_inbound.mixed_public_port", Type: "integer", Description: "Externally advertised port for the shared Mixed listener."},
				{Name: "shared_inbound.mixed_public_tls", Type: "boolean", Description: "Whether the shared Mixed public endpoint terminates TLS."},
				{Name: "shared_inbound.ws_public_host", Type: "string", Description: "Externally advertised host for the shared websocket listener."},
				{Name: "shared_inbound.ws_public_port", Type: "integer", Description: "Externally advertised port for the shared websocket listener."},
				{Name: "shared_inbound.include_in_per_service", Type: "boolean", Description: "Also carry websocket services through the shared listener while in per_service mode."},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_settings", Meaning: "Validation failed, for example a shared port that collides with a managed port."},
			},
		},
		{
			ID:          "routing_rules.read",
			Method:      http.MethodGet,
			Path:        "/api/v1/routing-rules",
			Summary:     "Read the traffic routing rules: which destinations go direct, which use a proxy group, and in what order they are evaluated.",
			Auth:        "api-key",
			ResponseRef: "The routing rule document.",
			SeeAlso:     []string{"routing_rules.update"},
		},
		{
			ID:      "routing_rules.update",
			Method:  http.MethodPut,
			Path:    "/api/v1/routing-rules",
			Summary: "Replace the routing rules. Evaluation follows the rule order, so a broad rule placed first shadows every rule after it.",
			Auth:    "api-key",
			Fields: []CapabilityField{
				{Name: "rules", Type: "array<object>", Description: "Ordered rules. Each rule matches a destination and names a target proxy group or DIRECT.", Example: []any{map[string]any{"match": "geosite:cn", "target": "DIRECT"}}},
			},
			Errors: []CapabilityError{
				{Status: 422, Code: "invalid_routing_rules", Meaning: "Validation failed, often a target that names no existing group."},
			},
		},
		{
			ID:          "residential.presets.read",
			Method:      http.MethodGet,
			Path:        "/api/v1/residential/presets",
			Summary:     "List vendor presets. Read this before creating a provider: it gives the exact protocol, gateway host and port, username template, rotation mode and TTL the vendor expects, so an agent does not have to guess them.",
			Auth:        "api-key",
			ResponseRef: "Preset list, each marked with whether it was verified against the vendor's documentation.",
		},
		{
			ID:         "residential.ctl",
			Method:     http.MethodPost,
			Path:       "/ctl/<control-token>/...",
			Summary:    "Claim, heartbeat and release a residential session. This is the one control-plane call a consumer makes itself; the token is channel-scoped and can burn provider quota, so it must never be handed to a read-only consumer.",
			Auth:       "token in path",
			PathParams: []string{"control-token: the channel's control token", "action: one of claim, heartbeat, release"},
			Errors: []CapabilityError{
				{Status: 409, Code: "lease_held", Meaning: "Another holder owns the session. Session operations are compare-and-set on an allocation version; re-read the session before retrying."},
				{Status: 429, Code: "rotate_rate_limited", Meaning: "The channel's rotation rate limit was hit."},
			},
			SeeAlso: []string{"docs/CONSUMER_INTEGRATION_CONTRACT.md"},
		},
	}
}

// capabilityWorkflows returns the workflows section of the catalog. It is data only: see capabilities.go for the types and the live enum wiring.
func capabilityWorkflows() []CapabilityWorkflow {
	return []CapabilityWorkflow{
		{
			ID:          "fastest_working_proxy",
			Summary:     "Reach a published, usable proxy in the fewest calls.",
			Description: "A listener that references an empty group carries no traffic, so the subscription must be refreshed before the group is created. The refresh is what makes the group's source_spec match anything.",
			FastPath:    "If nodes already exist (GET /api/v1/nodes returns some), skip steps 1-2 and go straight to proxy_service.create.",
			Steps: []string{
				"POST /api/v1/subscriptions — register the source. Skip when nodes already exist.",
				"POST /api/v1/subscriptions/<id>/refresh — fetch it, so nodes now exist. Skip when nodes already exist.",
				"GET /api/v1/nodes — confirm the refresh produced members.",
				"POST /api/v1/proxy-services — create the group and its listener together. The group is rolled back if the listener fails, so this call is all-or-nothing.",
				"GET /api/v1/listeners — read back share_path.",
				"Share share_path with the consumer, which then reads GET /nodes/<share-token> (or imports /sub/<share-token>) and dials the nodes itself.",
			},
		},
		{
			ID:          "chained_proxy",
			Summary:     "Route through an intermediate hop before reaching the final destination.",
			Description: "Chaining exists only for residential providers. upstream_proxy_group_id on a provider is the single entry point; there is no generic chain field on a plain group or listener. The intermediate group is compiled into the data plane as a dialer proxy, and the vendor gateway is never exposed to the consumer: the published node always names this control plane's own entry point.",
			Steps: []string{
				"Create and publish the intermediate group normally (workflow fastest_working_proxy).",
				"GET /api/v1/proxy-groups — take the intermediate group id.",
				"POST /api/v1/residential/providers with upstream_proxy_group_id set to that group.",
				"POST /api/v1/residential/channels — publish the channel. Consumers see only this control plane's entry point; the chain is transparent to them.",
			},
		},
	}
}

// capabilityNotSupported returns the notsupported section of the catalog. It is data only: see capabilities.go for the types and the live enum wiring.
func capabilityNotSupported() []string {
	return []string{
		"This control plane never carries proxy traffic. It configures a separate Mihomo data plane; there is no path where a control-plane process proxies a user request.",
		"It does not poll or rank nodes for a consumer. GET /nodes/<share-token> is a pure read, and selection, retry and rotation scheduling belong to the consumer. The one server-side exception is a residential /ctl/ session call, which the consumer still initiates.",
		"Chaining is residential-only. A plain subscription node cannot chain; upstream_proxy_group_id on a residential provider is the only chain entry point.",
		"'Supports all protocols' is false and must not be claimed: the supported set is what the installed Mihomo build supports, exposed as the node_protocol enum.",
		"WebSocket paths are not an authentication mechanism. A published ws service still requires credentials.",
	}
}

// capabilityRelated returns the related section of the catalog. It is data only: see capabilities.go for the types and the live enum wiring.
func capabilityRelated() []string {
	return []string{
		"docs/CONSUMER_INTEGRATION_CONTRACT.md",
		"docs/ARCHITECTURE.md",
	}
}
